chat_model:
  init_args:
    model: gemini-3-pro-high
    model_provider: openai
    api_key: sk-antigravity
    base_url: http://127.0.0.1:8045/v1
  max_requests_per_minute: 60
  max_requests_per_day: 1000

image_generator:
  class_path: tools.ImageGeneratorGeminiOpenAI
  init_args:
    api_key: sk-antigravity
    base_url: http://127.0.0.1:8045/v1
    model: gemini-3-pro-image
  max_requests_per_minute: 20
  max_requests_per_day: 500

video_generator:
  class_path: tools.VideoGeneratorVeoGoogleAPI
  init_args:
    api_key: AIzaSyB0f3v06E0cClck6VZ7EazrAL9TOX6J4Ps
  max_requests_per_minute: 2
  max_requests_per_day: 50

working_dir: .working_dir/idea2video_gemini
