chat_model:
  init_args:
    model: gemini-3-pro-high
    model_provider: openai
    api_key: sk-antigravity
    base_url: http://127.0.0.1:8045/v1
  max_requests_per_minute: 60
  max_requests_per_day: 1000

image_generator:
  class_path: tools.ImageGeneratorGeminiOpenAI
  init_args:
    api_key: sk-antigravity
    base_url: http://127.0.0.1:8045/v1
    model: gemini-3-pro-image
  max_requests_per_minute: 20
  max_requests_per_day: 500

video_generator:
  class_path: tools.VideoGeneratorDoubaoSeedanceYunwuAPI
  init_args:
    api_key: f60ed7c4-1e3f-468e-b00f-bcbe6db25e9d
    t2v_model: ep-20260116195359-29s4r
    ff2v_model: ep-20260116195359-29s4r
    flf2v_model: ep-20260116195359-29s4r
  max_requests_per_minute: 20
  max_requests_per_day: 500

working_dir: .working_dir/0117
